<?php

namespace Database\Seeders;

use App\Models\Project;
use Illuminate\Database\Seeder;
use Illuminate\Support\Str;

class ProjectSeeder extends Seeder
{
    public function run(): void
    {
        $projects = [
            // =========================================================================
            // Competent Communication (CC) Manual — Traditional Track (Projects 1 to 10)
            // =========================================================================
            [
                'name'             => 'Ice Breaker',
                'track'            => 'Competent Communication',
                'level'            => 1,
                'min_minutes'      => 4,
                'max_minutes'      => 6,
                'default_duration' => '4-6 mins',
                'overview'         => 'To begin speaking before an audience and introduce yourself to your fellow club members.',
                'objectives'       => 'To begin speaking before an audience; To discover speaking characteristics you already have and skills that need development; To introduce yourself to your fellow club members.',
                'evaluator_notes'  => 'Notice if the speech had a clear beginning, middle, and end. Praise personal stories, vocal clarity, and genuine delivery. Offer encouraging and positive feedback for the speaker\'s first presentation.',
                'sort_order'       => 10,
            ],
            [
                'name'             => 'Organize Your Speech',
                'track'            => 'Competent Communication',
                'level'            => 2,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Create a clear, logical structure (opening, body, conclusion) with smooth transitions so listeners can easily follow.',
                'objectives'       => 'Select an appropriate outline which allows listeners to easily follow and understand your speech; Make your message clear with supporting material directly contributing to that message; Use appropriate transitions when moving from one idea to another; Create a strong opening and conclusion.',
                'evaluator_notes'  => 'Assess the clarity of the speech outline. Did the opening grab attention? Were transitions between main points clear and smooth? Did the conclusion reinforce the central message?',
                'sort_order'       => 20,
            ],
            [
                'name'             => 'Get to the Point',
                'track'            => 'Competent Communication',
                'level'            => 3,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Formulate general and specific speech objectives, staying sharply focused on your primary goal without unnecessary detours.',
                'objectives'       => 'Select a speech topic and determine its general and specific purposes; Organize the speech in a manner that best achieves those purposes; Ensure the beginning, body, and conclusion tie directly to the central purpose; Project sincerity and conviction.',
                'evaluator_notes'  => 'Could the audience clearly articulate the speaker\'s primary purpose? Did every supporting point reinforce that purpose? Was the speaker confident and sincere?',
                'sort_order'       => 30,
            ],
            [
                'name'             => 'How to Say It',
                'track'            => 'Competent Communication',
                'level'            => 4,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Select precise, evocative, and vivid words. Harness rhetorical devices to heighten impact while eliminating jargon and wordiness.',
                'objectives'       => 'Select the right words and sentence structures to communicate ideas clearly, accurately, and vividly; Use rhetorical devices (metaphors, similes, alliteration, triads) to enhance and emphasize ideas; Eliminate jargon and wordiness.',
                'evaluator_notes'  => 'Note the speaker\'s word choices. Were descriptions clear, accurate, and vivid? Did rhetorical devices strengthen the message? Was the speech free of clichés and unnecessary buzzwords?',
                'sort_order'       => 40,
            ],
            [
                'name'             => 'Your Body Speaks',
                'track'            => 'Competent Communication',
                'level'            => 5,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Use purposeful movement, expressive hand gestures, facial animation, and confident eye contact to reinforce your verbal message.',
                'objectives'       => 'Use stance, movement, gestures, facial expressions, and eye contact to express your message and achieve your speech\'s purpose; Ensure body language appears natural, purposeful, and spontaneous.',
                'evaluator_notes'  => 'Observe physical movements: Did the speaker move with purpose? Were hand gestures natural and uninhibited? Was eye contact maintained across the entire room?',
                'sort_order'       => 50,
            ],
            [
                'name'             => 'Vocal Variety',
                'track'            => 'Competent Communication',
                'level'            => 6,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Modulate your pitch, speaking rate, volume, and use dramatic pauses to convey emotion and keep your listeners captivated.',
                'objectives'       => 'Use voice volume, pitch, rate, and quality to reflect and add meaning and interest to your message; Use pauses purposefully to enhance your speech; Achieve natural vocal modulations.',
                'evaluator_notes'  => 'Listen for vocal expression: Did the speaker vary pitch, rate, and loudness? Were dramatic pauses used effectively to emphasize key points? Was the voice natural and audible?',
                'sort_order'       => 60,
            ],
            [
                'name'             => 'Research Your Topic',
                'track'            => 'Competent Communication',
                'level'            => 7,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Collect verifiable facts, data, statistics, expert quotes, and historical examples from reputable sources to substantiate your assertions.',
                'objectives'       => 'Collect information about your topic from numerous sources; Carefully support your points and opinions with specific facts, examples, and illustrations; Cite your sources accurately and seamlessly.',
                'evaluator_notes'  => 'Did the speaker demonstrate thorough research? Were sources cited smoothly without interrupting speech flow? Was data clear, accurate, and relevant?',
                'sort_order'       => 70,
            ],
            [
                'name'             => 'Get Comfortable with Visual Aids',
                'track'            => 'Competent Communication',
                'level'            => 8,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Enhance listener comprehension by designing and presenting clear, impactful visual aids (slides, props, flipcharts, or whiteboards).',
                'objectives'       => 'Select visual aids that are appropriate for your message and the audience; Use visual aids with correct timing and technique; Display them so that everyone can see them clearly.',
                'evaluator_notes'  => 'Did visual aids enhance or distract from the presentation? Did the speaker maintain eye contact with the audience instead of looking solely at the slides/props?',
                'sort_order'       => 80,
            ],
            [
                'name'             => 'Persuade with Power',
                'track'            => 'Competent Communication',
                'level'            => 9,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Combine credibility (ethos), logical reasoning (logos), and emotional appeal (pathos) to persuade the audience toward a clear call to action.',
                'objectives'       => 'Present a persuasive message that appeals to audience interests, desires, or emotions; Use logic, evidence, and emotional appeal to build a compelling case; Inspire the audience to adopt your view or take specific action.',
                'evaluator_notes'  => 'How compelling was the persuasion? Did the speaker balance logical argument with emotional resonance? Was the final call to action clear and motivating?',
                'sort_order'       => 90,
            ],
            [
                'name'             => 'Inspire Your Audience',
                'track'            => 'Competent Communication',
                'level'            => 10,
                'min_minutes'      => 8,
                'max_minutes'      => 10,
                'default_duration' => '8-10 mins',
                'overview'         => 'The capstone project of the Competent Communication manual. Deliver an inspiring, motivational keynote that touches hearts and challenges listeners to greatness.',
                'objectives'       => 'Inspire the audience by appealing to noble motives and challenging them to achieve a higher goal or embrace a vision; Use stories, anecdotes, and quotes to dramatize your message; Create a powerful, memorable, and uplifting conclusion.',
                'evaluator_notes'  => 'Did the speech inspire and uplift the club? Was the delivery heartfelt, passionate, and polished? Did the conclusion leave a lasting, inspirational impact?',
                'sort_order'       => 100,
            ],

            // =========================================================================
            // Advanced Communication: Storytelling
            // =========================================================================
            [
                'name'             => 'The Folk Tale',
                'track'            => 'Storytelling',
                'level'            => 1,
                'min_minutes'      => 6,
                'max_minutes'      => 8,
                'default_duration' => '6-8 mins',
                'overview'         => 'Tell a traditional folk tale, myth, or legend adapted for a modern audience with engaging character development and vocal colors.',
                'objectives'       => 'Prepare and tell a traditional folk tale; Use vocal variety, body language, and vivid descriptions to bring the story to life.',
                'evaluator_notes'  => 'Did the speaker vividly establish characters and setting? Was the moral or central message clear?',
                'sort_order'       => 110,
            ],
            [
                'name'             => 'Let\'s Tell a Story',
                'track'            => 'Storytelling',
                'level'            => 2,
                'min_minutes'      => 6,
                'max_minutes'      => 8,
                'default_duration' => '6-8 mins',
                'overview'         => 'Create a personal or fictional original narrative structured with rising action, climax, and emotional resonance.',
                'objectives'       => 'Structure an original narrative with clear plot points, conflict, climax, and resolution.',
                'evaluator_notes'  => 'Assess suspense, character dialogue, and pacing throughout the narrative arc.',
                'sort_order'       => 120,
            ],
            [
                'name'             => 'The Moral of the Story',
                'track'            => 'Storytelling',
                'level'            => 3,
                'min_minutes'      => 6,
                'max_minutes'      => 8,
                'default_duration' => '6-8 mins',
                'overview'         => 'Share a story that teaches an important ethical, philosophical, or life lesson without being heavy-handed.',
                'objectives'       => 'Deliver a narrative where the theme or lesson emerges naturally from the characters\' actions and consequences.',
                'evaluator_notes'  => 'Was the moral compelling and smoothly integrated, or did it feel tacked on at the end?',
                'sort_order'       => 130,
            ],
            [
                'name'             => 'The Touching Story',
                'track'            => 'Storytelling',
                'level'            => 4,
                'min_minutes'      => 6,
                'max_minutes'      => 8,
                'default_duration' => '6-8 mins',
                'overview'         => 'Evoke deep emotions (compassion, empathy, warmth, or nostalgia) through a poignant, heartfelt narrative.',
                'objectives'       => 'Build emotional connection with listeners through sensitive detail, empathy, and sincere delivery.',
                'evaluator_notes'  => 'How effectively did the speaker convey emotional vulnerability and connect with the room?',
                'sort_order'       => 140,
            ],
            [
                'name'             => 'Bringing History to Life',
                'track'            => 'Storytelling',
                'level'            => 5,
                'min_minutes'      => 7,
                'max_minutes'      => 9,
                'default_duration' => '7-9 mins',
                'overview'         => 'Take a historical event or biography and tell it as an exciting, dramatic story rather than dry dates and facts.',
                'objectives'       => 'Humanize historical figures, recreate historical atmospheres, and build dramatic tension from real events.',
                'evaluator_notes'  => 'Did the presentation feel like an engaging story rather than a dry history lecture?',
                'sort_order'       => 150,
            ],

            // =========================================================================
            // Advanced Communication: The Entertaining Speaker
            // =========================================================================
            [
                'name'             => 'The Entertaining Speech',
                'track'            => 'The Entertaining Speaker',
                'level'            => 1,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Entertain the audience by combining an amusing narrative or perspective with a meaningful underlying thought.',
                'objectives'       => 'Keep audience entertained while delivering an organized speech with a clear point.',
                'evaluator_notes'  => 'Did the audience smile and laugh? Was the entertainment balanced with a clear speech takeaway?',
                'sort_order'       => 160,
            ],
            [
                'name'             => 'Resources for Entertainment',
                'track'            => 'The Entertaining Speaker',
                'level'            => 2,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Draw entertainment material from personal experiences, observations, drama, wit, and wordplay.',
                'objectives'       => 'Demonstrate diverse techniques for creating amusement beyond standard one-liner jokes.',
                'evaluator_notes'  => 'Assess the variety of comedic and dramatic devices used by the speaker.',
                'sort_order'       => 170,
            ],
            [
                'name'             => 'Make Them Laugh',
                'track'            => 'The Entertaining Speaker',
                'level'            => 3,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Incorporate humorous stories and witty observations with precise comedic timing and pauses.',
                'objectives'       => 'Prepare and deliver a humorous speech using setup, punchlines, callbacks, and pauses.',
                'evaluator_notes'  => 'Watch the timing of punchlines and the speaker\'s ability to ride audience laughter.',
                'sort_order'       => 180,
            ],
            [
                'name'             => 'A Dramatic Talk',
                'track'            => 'The Entertaining Speaker',
                'level'            => 4,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Use dramatic acting techniques, emotional intensity, dialogue, and vocal contrast to entertain.',
                'objectives'       => 'Engage the audience through theatrical drama, expressive role-playing, and vivid storytelling.',
                'evaluator_notes'  => 'Evaluate how convincingly the speaker portrayed different emotions and character voices.',
                'sort_order'       => 190,
            ],
            [
                'name'             => 'Speaking After Dinner',
                'track'            => 'The Entertaining Speaker',
                'level'            => 5,
                'min_minutes'      => 8,
                'max_minutes'      => 10,
                'default_duration' => '8-10 mins',
                'overview'         => 'Master the classic after-dinner speech: lighthearted, witty, celebratory, and concluding with a warm, memorable point.',
                'objectives'       => 'Deliver an extended entertaining presentation suited for banquets, dinners, and special gatherings.',
                'evaluator_notes'  => 'Was the tone festive and entertaining throughout? Was the ending gracious and memorable?',
                'sort_order'       => 200,
            ],

            // =========================================================================
            // Advanced Communication: Speaking to Inform
            // =========================================================================
            [
                'name'             => 'The Speech to Inform',
                'track'            => 'Speaking to Inform',
                'level'            => 1,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Present new information or clarify a complex topic so the audience gains actionable understanding.',
                'objectives'       => 'Select a new or complex topic; Present clear facts and explanations that broaden audience knowledge.',
                'evaluator_notes'  => 'Was the subject matter easy to understand? Did the speaker avoid unnecessary confusion?',
                'sort_order'       => 210,
            ],
            [
                'name'             => 'Resources for Informing',
                'track'            => 'Speaking to Inform',
                'level'            => 2,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Deep dive into research sources, contrasting differing perspectives and presenting unbiased findings.',
                'objectives'       => 'Use multiple authoritative references and present balanced, factual information.',
                'evaluator_notes'  => 'Check the quality and objectivity of the sources cited.',
                'sort_order'       => 220,
            ],
            [
                'name'             => 'The Demonstration Talk',
                'track'            => 'Speaking to Inform',
                'level'            => 3,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Show and explain how to do something or how something works through a step-by-step physical demonstration.',
                'objectives'       => 'Demonstrate a process clearly while maintaining speaker-audience engagement and good stage control.',
                'evaluator_notes'  => 'Could audience members replicate the process themselves based on the demonstration?',
                'sort_order'       => 230,
            ],
            [
                'name'             => 'A Fact-Finding Report',
                'track'            => 'Speaking to Inform',
                'level'            => 4,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Investigate a specific situation, problem, or initiative and present findings, analysis, and recommendations.',
                'objectives'       => 'Deliver an executive-style briefing summarizing research methodology, findings, and logical recommendations.',
                'evaluator_notes'  => 'Assess the clarity of the analysis and the practical feasibility of recommendations.',
                'sort_order'       => 240,
            ],
            [
                'name'             => 'The Abstract Concept',
                'track'            => 'Speaking to Inform',
                'level'            => 5,
                'min_minutes'      => 6,
                'max_minutes'      => 8,
                'default_duration' => '6-8 mins',
                'overview'         => 'Explain an intangible, complex, or philosophical concept (e.g. quantum physics, love, justice) using analogies and examples.',
                'objectives'       => 'Make abstract concepts concrete, relatable, and easy to grasp for a general audience.',
                'evaluator_notes'  => 'Did the analogies clarify the abstract idea? Was the explanation engaging and accessible?',
                'sort_order'       => 250,
            ],

            // =========================================================================
            // Advanced Communication: Persuasive Speaking
            // =========================================================================
            [
                'name'             => 'The Effective Salesperson',
                'track'            => 'Persuasive Speaking',
                'level'            => 1,
                'min_minutes'      => 8,
                'max_minutes'      => 12,
                'default_duration' => '8-12 mins',
                'overview'         => 'Pitch a product, service, or solution by identifying prospect needs and demonstrating clear benefits.',
                'objectives'       => 'Conduct a consultative sales presentation, overcome objections, and ask for the sale.',
                'evaluator_notes'  => 'Did the speaker focus on benefits rather than just features? Was the close confident?',
                'sort_order'       => 260,
            ],
            [
                'name'             => 'Conquering the Cold Call',
                'track'            => 'Persuasive Speaking',
                'level'            => 2,
                'min_minutes'      => 10,
                'max_minutes'      => 14,
                'default_duration' => '10-14 mins',
                'overview'         => 'Role-play an introductory cold contact with an unfamiliar prospect, establish rapport, and secure a follow-up meeting.',
                'objectives'       => 'Break the ice with a hesitant prospect, capture interest within the first 60 seconds, and handle initial resistance.',
                'evaluator_notes'  => 'Observe composure, active listening, and agility in handling prospect resistance.',
                'sort_order'       => 270,
            ],
            [
                'name'             => 'The Winning Proposal',
                'track'            => 'Persuasive Speaking',
                'level'            => 3,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Formulate and pitch an organizational proposal or strategic business case to decision-makers.',
                'objectives'       => 'Present problems, proposed solutions, cost-benefit analysis, and implementation milestones.',
                'evaluator_notes'  => 'Was the proposal practical, well-costed, and persuasive to decision-makers?',
                'sort_order'       => 280,
            ],
            [
                'name'             => 'Addressing the Opposition',
                'track'            => 'Persuasive Speaking',
                'level'            => 4,
                'min_minutes'      => 7,
                'max_minutes'      => 9,
                'default_duration' => '7-9 mins',
                'overview'         => 'Present a controversial viewpoint, anticipate opposing arguments, and respectfully rebut counterclaims.',
                'objectives'       => 'Acknowledge valid objections without being defensive, and demonstrate the superiority of your position.',
                'evaluator_notes'  => 'Did the speaker treat opposing viewpoints respectfully while firmly maintaining their thesis?',
                'sort_order'       => 290,
            ],
            [
                'name'             => 'The Persuasive Leader',
                'track'            => 'Persuasive Speaking',
                'level'            => 5,
                'min_minutes'      => 6,
                'max_minutes'      => 8,
                'default_duration' => '6-8 mins',
                'overview'         => 'Deliver a rallying vision speech that inspires a team or organization to commit to an ambitious collective mission.',
                'objectives'       => 'Articulate a shared vision, unite listeners around core values, and instill confidence in achieving the goal.',
                'evaluator_notes'  => 'Did the speech communicate strong leadership presence and inspire commitment?',
                'sort_order'       => 300,
            ],

            // =========================================================================
            // Advanced Communication: Special Occasion Speeches
            // =========================================================================
            [
                'name'             => 'Mastering the Toast',
                'track'            => 'Special Occasion Speeches',
                'level'            => 1,
                'min_minutes'      => 2,
                'max_minutes'      => 3,
                'default_duration' => '2-3 mins',
                'overview'         => 'Deliver a warm, witty, and sincere toast honoring an individual, achievement, or milestone occasion.',
                'objectives'       => 'Convey affection, humor, and respect succinctly; Lead the audience smoothly into raising their glasses.',
                'evaluator_notes'  => 'Was the toast appropriately brief, heartfelt, and memorable without embarrassing the honoree?',
                'sort_order'       => 310,
            ],
            [
                'name'             => 'Speaking in Praise',
                'track'            => 'Special Occasion Speeches',
                'level'            => 2,
                'min_minutes'      => 5,
                'max_minutes'      => 7,
                'default_duration' => '5-7 mins',
                'overview'         => 'Deliver a tribute, eulogy, or speech of dedication honoring a person, institution, or historic milestone.',
                'objectives'       => 'Pay homage with dignity, emotional depth, vivid memories, and enduring inspiration.',
                'evaluator_notes'  => 'Assess emotional sincerity, poetic language, and respect shown to the subject.',
                'sort_order'       => 320,
            ],
            [
                'name'             => 'The Roasting',
                'track'            => 'Special Occasion Speeches',
                'level'            => 3,
                'min_minutes'      => 3,
                'max_minutes'      => 5,
                'default_duration' => '3-5 mins',
                'overview'         => 'Poke gentle, playful, and affectionate fun at a well-known friend or colleague while keeping warmth and respect intact.',
                'objectives'       => 'Deliver witty, good-natured ribbing that entertains the room while making the honoree feel loved.',
                'evaluator_notes'  => 'Did the roast strike the right balance between sharp humor and underlying affection?',
                'sort_order'       => 330,
            ],
            [
                'name'             => 'Presenting an Award',
                'track'            => 'Special Occasion Speeches',
                'level'            => 4,
                'min_minutes'      => 3,
                'max_minutes'      => 4,
                'default_duration' => '3-4 mins',
                'overview'         => 'Present an award by explaining its significance, highlighting the recipient\'s achievements, and building suspense.',
                'objectives'       => 'Highlight the prestige of the award and honor the winner\'s contributions enthusiastically.',
                'evaluator_notes'  => 'Did the presenter establish the importance of the award and create genuine excitement?',
                'sort_order'       => 340,
            ],
            [
                'name'             => 'Accepting an Award',
                'track'            => 'Special Occasion Speeches',
                'level'            => 5,
                'min_minutes'      => 3,
                'max_minutes'      => 4,
                'default_duration' => '3-4 mins',
                'overview'         => 'Accept an honor with genuine humility, grace, enthusiasm, and heartfelt acknowledgment of supporters.',
                'objectives'       => 'Express heartfelt gratitude, acknowledge mentors and team members, and show gracious humility.',
                'evaluator_notes'  => 'Was the acceptance speech sincere, unpretentious, and delivered within the time limit?',
                'sort_order'       => 350,
            ],
        ];

        foreach ($projects as $proj) {
            $uniqueSlug = Str::slug($proj['track'] . '-' . $proj['name']);
            if ($proj['name'] === 'Ice Breaker' && $proj['track'] === 'Competent Communication') {
                $existing = Project::where('slug', 'ice-breaker')->orWhere('slug', $uniqueSlug)->first();
                if ($existing) {
                    $existing->update(array_merge($proj, ['slug' => $uniqueSlug]));
                    continue;
                }
            }

            Project::updateOrCreate(
                ['slug' => $uniqueSlug],
                array_merge($proj, ['slug' => $uniqueSlug])
            );
        }
    }
}
